[package]
name = "ooxml-version-control"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
walkdir = "2.5.0"
zip = "2.2.0"
tempfile = "3.13.0"
log = "0.4.22"
env_logger = "0.11.5"
quick-xml = { version = "0.36.2", features = ["serialize"] }
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
test-log = "0.2.16"
